blank_issues_enabled: true
contact_links:
  - name: Battle for Wesnoth Forums
    url: https://forums.wesnoth.org/viewtopic.php?f=8&t=33745
    about: Ask general questions about the campaign here. You can also report issues/bugs here.
